# Generated by Django 5.0.6 on 2024-07-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_stockdata_high_stockdata_low_stockdata_open_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='change_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
