# Generated by Django 4.2.13 on 2024-07-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_stockdata_change_stockdata_change_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='change_percent',
            field=models.CharField(max_length=10),
        ),
    ]
