# Generated by Django 5.0.6 on 2024-06-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracking', '0003_customlabel_current_amount_customlabel_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlabel',
            name='is_expense',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget_tracking.customlabel'),
        ),
    ]
