# Generated by Django 5.0.6 on 2024-06-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracking', '0004_alter_transaction_label'),
        ('budget_tracking', '0004_customlabel_is_expense_alter_transaction_label'),
    ]

    operations = [
    ]
